# Generated by Django 3.2.7 on 2021-09-12 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.CharField(max_length=50, verbose_name='Альбом')),
                ('description', models.TextField(max_length=150, verbose_name='Описаніє')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', verbose_name='Зображення')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.album', verbose_name='Альбом')),
            ],
        ),
    ]
