# Generated by Django 3.2.7 on 2021-09-13 07:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])], verbose_name='Відіо')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.album', verbose_name='Альбом')),
            ],
        ),
    ]
