# Generated by Django 3.2.7 on 2021-09-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='photos_get', to='photos.Photo', verbose_name='Зображення'),
        ),
    ]
