# Generated by Django 3.2.7 on 2021-09-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_album_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='movies',
            field=models.ManyToManyField(blank=True, related_name='movies_get', to='photos.Movie', verbose_name='Відіо'),
        ),
    ]
