# Generated by Django 3.2.7 on 2021-09-14 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_album_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photos.album', verbose_name='Альбом'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photos.album', verbose_name='Альбом'),
        ),
    ]
