# Generated by Django 3.2.7 on 2021-09-15 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_alter_photo_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='movies',
        ),
        migrations.RemoveField(
            model_name='album',
            name='photos',
        ),
    ]
