# Generated by Django 3.2.7 on 2021-09-15 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_auto_20210915_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_type', models.CharField(max_length=50, verbose_name='Тип альбому')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='album_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photos.albumtype', verbose_name='Тип'),
        ),
    ]
